name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  actions: write
  contents: write

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Version 6.0.2
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # Version 5.0.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # Version 6.2.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install tox"
        run: |
          python -m pip install --upgrade tox tox-gh-actions

      - name: "Run pre-commit with tox"
        run: python -m tox -e precommit
