name: "Validate"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Version 6.0.2

      - name: "Run hassfest validation"
        uses: home-assistant/actions/hassfest@5752577ea7cc5aefb064b0b21432f18fe4d6ba90 # Version 11 September 2025

  hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Version 6.0.2

      - name: "Run HACS validation"
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # Version 22.5.0
        with:
          category: "integration"
